### ISSUE TITLE
On OSX El Capitan only first page displays

### ISSUE THREAD

**Issue by gpasa** [mpflanzer/splitshow#36]
Hi,
I'm new to splitshow and I just tried it on El Capitan.
It loads ok, then I select my file and chose the two screens and go fullscreen (would it be possible to implement working in windowed mode with the beamer screen updating its data ?).
The first page appears on the beamer and the notes on the fullscreen of the computer, all ok.
But then when I go to the next slide I only get blank pages.
If I resize the PC screen, it displays the notes, but the beamer screen is still blank.

**Comment by Cyrkhan** [comment]
Same problem for me, and it seems restricted to El Capitan : before upgrading, SplitShow worked fine on Yosemite.

**Comment by jcatumba** [comment]
Same issue over here. I can help with code but need some advice how to proceed with this particular error.

**Comment by mpflanzer** [comment]
Thanks. I am still not sure why exactly it stopped working on El Capitan but it is something about using the same PDF page (i.e. the same object) for multiple displays.
I pushed a workaround and updated both releases:

For 10.10 an above: https://github.com/mpflanzer/splitshow/releases/tag/v0.9.5-alpha2
Below 10.10 (no storyboards): https://github.com/mpflanzer/splitshow/releases/tag/v0.9.6-alpha2

Please let me know if this solves the problem for you. I am currently working on a complete redesign to cover some of the other mentioned limitation. But it might take me some more time to finish it. At the moment I do not find much time.

**Comment by Cyrkhan** [comment]
Hello. The problem seems to be fixed with the new 0.9.5 or 0.9.6 alpha2 updates. I only notice an awkward "jump" of the screen when passing from one frame to another, as if the first frame was erased before loading of the following. So the presentation seems not as smooth as it was before.

**Comment by mpflanzer** [comment]
I updated both release with a new patch. I have not seen the "jumping" in the first case either but it should be fixed now.

I only noticed that the pages seem to take a little while to load when they are viewed the first time (on each display). Then there are some "white flickering" when switching to the next slide. Once the slide has been view going back and forth again creates a smooth transition. I found no solution how to change this although the native Preview app does not seems to have this problem. I am also not sure if the same behaviour was noticeable prior El Capitan.

Please let me know if there are still some problems!

**Comment by danielberlin** [comment]
The "white flickering" and the little page loading delay at each display appeared since El Capitan, I remember that for sure. My first quick test showed problems with notes pages – if not every page has its corresponding notes page and slides are animated (`<1->` etc.), then always the last animation step is not displayed anymore but already the next slide.

**Comment by Cyrkhan** [comment]
I try the last version of SplitShow with two long Beamer presentations. Apart from the white flickering at the first display of a new frame, I notice two things :
- first, I need to specify in the Beamer TeX code \setbeameroption{show notes on second screen=right} in order to really obtain the main display on the additional screen rather than on my laptop screen. With "second screen=left", notes and main slide are inverted, although I correctly choose main and helper displays with SplitShow menus.
 - second, in both cases, SplitShow blocked during first try of the presentations (with spinning wheel running indefinitely). After force quitting and opening again SplitShow,  the presentation can be visualized till it end.

So it works, but it always need to be tested before the ''real'' presentation.

Regards,
Cyril

> Le 7 déc. 2015 à 10:50, danielberlin <notifications@github.com> a écrit :
> 
> The "white flickering" and the little page loading delay at each display appeared since El Capitan, I remember that for sure. My first quick test showed problems with notes pages – if not every page has its corresponding notes page and slides are animated (<1-> etc.), then always the last animation step is not displayed anymore but already the next slide.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mpflanzer/splitshow/issues/36#issuecomment-162466548>.
> 

Cyril LANGLOIS
Cyril.Langlois@normalesup.org
Tél : 06 89 05 68 22

http://www.normalesup.org/~clanglois/Index.html
https://plus.google.com/photos/110867195811650034299/albums?banner=pwa&partnerid=pwrd1
§ ---------------------- §
"Les hommes ne souffrent que d'une seule maladie : l'ignorance. A ce mal, il n'y a qu'un seul remède: l'instruction. Mais il ne s'agit pas de prendre ce remède à doses homéopathiques. Il faut le prendre par seaux entiers, et par barriques de quarante seaux." Dmitri Pissariev

**Comment by Cyrkhan** [comment]
Hello,
One more problem running SplitShow on ElCapitan : if the screen saver starts during the presentation, SplitShow seems to freeze and must be quitted in order to come back to the finder.

Regards,
Cyril

> Le 7 déc. 2015 à 11:14, Cyril Langlois <Cyril.Langlois@normalesup.org> a écrit :
> 
> I try the last version of SplitShow with two long Beamer presentations. Apart from the white flickering at the first display of a new frame, I notice two things :
> - first, I need to specify in the Beamer TeX code \setbeameroption{show notes on second screen=right} in order to really obtain the main display on the additional screen rather than on my laptop screen. With "second screen=left", notes and main slide are inverted, although I correctly choose main and helper displays with SplitShow menus.
>  - second, in both cases, SplitShow blocked during first try of the presentations (with spinning wheel running indefinitely). After force quitting and opening again SplitShow,  the presentation can be visualized till it end.
> 
> So it works, but it always need to be tested before the ''real'' presentation.
> 
> Regards,
> Cyril
> 
>> Le 7 déc. 2015 à 10:50, danielberlin <notifications@github.com <mailto:notifications@github.com>> a écrit :
>> 
>> The "white flickering" and the little page loading delay at each display appeared since El Capitan, I remember that for sure. My first quick test showed problems with notes pages – if not every page has its corresponding notes page and slides are animated (<1-> etc.), then always the last animation step is not displayed anymore but already the next slide.
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/mpflanzer/splitshow/issues/36#issuecomment-162466548>.
>> 
> 

Cyril LANGLOIS
Cyril.Langlois@normalesup.org
Tél : 06 89 05 68 22

http://www.normalesup.org/~clanglois/Index.html
https://plus.google.com/photos/110867195811650034299/albums?banner=pwa&partnerid=pwrd1
§ ---------------------- §
"Les hommes ne souffrent que d'une seule maladie : l'ignorance. A ce mal, il n'y a qu'un seul remède: l'instruction. Mais il ne s'agit pas de prendre ce remède à doses homéopathiques. Il faut le prendre par seaux entiers, et par barriques de quarante seaux." Dmitri Pissariev

**Comment by mpflanzer** [comment]
Ok pushed and uploaded a new release of SplitShow. It is a mayor redesign which solves most of the problems and makes the code nicer. ;)

I will close this issue as it should be solved. The "white flickering" is still there but I cannot find a solution. And as it only happens the first time each slide is loaded I think it is not an urgent issue.

Please open new issues for problems you encounter. Thanks!
