### ISSUE TITLE
Some information in documentation on how to install

### ISSUE THREAD

**Issue by Ashutosh-Work** [mpflanzer/splitshow#46]
Some instructions on how to install this amazing piece of software would be very helpful.
I am a newbie to the world of git and coding. 
So my first instinct was to locate a dmg file, which I could not for the latest version. 
(It is there for the old google code version from 2008).

**Comment by mpflanzer** [comment]
If you don't want to build the SplitShow from source you can download the latest release: https://github.com/mpflanzer/splitshow/releases/tag/0.9.8-alpha2
The archive `SplitShow.app.zip` contains the prebuilt app. You just have to extract it and open the the `SplitShow.app` executable. There is no need to install anything.

*It might be that GateKeeper prevents to open SplitShow straight away because it is not signed with an Apple Developer ID. If that happens you can tell GateKeeper to open the app anyway by going to `System Preferences` -> `Security & Privacy`. In the general tab there will be a button to allow to open SplitShow.*

Let me know if you find problems with running SplitShow.

**Comment by lornajane** [comment]
These instructions worked for me 👍 

What help do you want, should I add the installation steps to the README?

**Comment by mpflanzer** [comment]
> These instructions worked for me 👍 

Glad to hear that! :)

> What help do you want, should I add the installation steps to the README?

That would be great if you had some time to update the README file with some useful instructions.

Regards,
Moritz
